import React,{useEffect,useState} from 'react'
import {BarChart3,CheckCircle2,Eye,FileText,Image,LayoutDashboard,LogOut,MonitorSmartphone,Palette,Plus,Save,Settings,ShieldCheck,Trash2,Users} from 'lucide-react'
import {defaultPrograms,defaultSettings} from './defaults'
import {supabase,supabaseEnabled} from './supabase'
const deepMerge=(base,extra)=>{if(Array.isArray(base))return Array.isArray(extra)?extra:base;if(base&&typeof base==='object'){const o={...base};Object.keys(extra||{}).forEach(k=>o[k]=k in base?deepMerge(base[k],extra[k]):extra[k]);return o}return extra??base}
const hydrateSettings=(data)=>{const n=deepMerge(defaultSettings,data||{});if(data?.preform?.fields){const fields={...data.preform.fields};if(fields.email){if(!fields.profession)fields.profession={...defaultSettings.preform.fields.profession};delete fields.email}if(!fields.address)fields.address={...defaultSettings.preform.fields.address};Object.keys(fields).forEach(k=>{if(fields[k]?.order==null&&defaultSettings.preform.fields[k]?.order!=null)fields[k]={...fields[k],order:defaultSettings.preform.fields[k].order}});n.preform.fields=fields}return n}
const iconOptions=[['users','Kullanıcılar'],['graduation','Öğrenci'],['heart','Destek'],['store','Esnaf'],['home','Ev'],['landmark','Emekli']]
export default function Admin(){
 const [auth,setAuth]=useState(null),[allowed,setAllowed]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[loginError,setLoginError]=useState(''),[tab,setTab]=useState('dashboard'),[settings,setSettings]=useState(defaultSettings),[programs,setPrograms]=useState(defaultPrograms),[banners,setBanners]=useState([]),[sessions,setSessions]=useState([]),[apps,setApps]=useState([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[clock,setClock]=useState(Date.now())
 useEffect(()=>{if(!supabaseEnabled)return;(async()=>{const {data:{session}}=await supabase.auth.getSession();if(session){setAuth(session);await checkAdmin(session.user.id)}})();const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setAuth(s));return()=>l.subscription.unsubscribe()},[])
 async function checkAdmin(uid){const {data,error}=await supabase.from('admins').select('user_id').eq('user_id',uid).maybeSingle();if(error){setLoginError(error.message);setAllowed(false);return}setAllowed(Boolean(data));if(data)await loadAll();else setLoginError('Bu kullanıcı yönetici olarak yetkilendirilmemiş.')}
 async function login(e){e.preventDefault();setLoginError('');const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)return setLoginError(error.message);setAuth(data.session);await checkAdmin(data.user.id)}
 async function logout(){await supabase.auth.signOut();setAllowed(false);setAuth(null)}
 async function loadAll(){const [{data:s},{data:p},{data:b},{data:v},{data:a}]=await Promise.all([supabase.from('site_settings').select('data').eq('id','main').maybeSingle(),supabase.from('programs').select('*').order('sort_order'),supabase.from('banners').select('*').order('sort_order'),supabase.from('demo_live_sessions').select('*').order('last_seen',{ascending:false}).limit(500),supabase.from('demo_applications').select('*').order('updated_at',{ascending:false}).limit(250)]);if(s?.data)setSettings(hydrateSettings(s.data));if(p?.length)setPrograms(p);setBanners(b||[]);setSessions(v||[]);
 const mapped=(a||[]).map(row=>({
   ...row,
   ...(row.payload||{}),
   id:row.id,
   status:row.status,
   submitted:row.submitted,
   created_at:row.created_at,
   updated_at:row.updated_at,
   programs:{title:(p||[]).find(x=>x.id===(row.payload||{}).program_id)?.title||'—'}
 }));
 setApps(mapped)}
 useEffect(()=>{if(!allowed||!supabaseEnabled)return;const ch=supabase.channel('admin-live-v4').on('postgres_changes',{event:'*',schema:'public',table:'demo_live_sessions'},loadAll).on('postgres_changes',{event:'*',schema:'public',table:'demo_applications'},loadAll).subscribe();return()=>supabase.removeChannel(ch)},[allowed])
 useEffect(()=>{if(!allowed)return;const t=setInterval(()=>setClock(Date.now()),5000);return()=>clearInterval(t)},[allowed])
 if(!supabaseEnabled)return <LoginShell><div className="admin-card"><h2>Supabase bağlantısı bekleniyor</h2></div></LoginShell>
 if(!auth||!allowed)return <LoginShell><form className="admin-card login" onSubmit={login}><div className="admin-logo"><ShieldCheck/></div><h1>Yönetim Paneli</h1><p>Yetkili demo yöneticisi girişi</p><label>E-posta<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required/></label><label>Şifre<input value={password} onChange={e=>setPassword(e.target.value)} type="password" required/></label>{loginError&&<div className="error">{loginError}</div>}<button className="primary full">Giriş yap</button></form></LoginShell>
 const menu=[['dashboard','Genel Bakış',LayoutDashboard],['global','Header / Footer',Palette],['home','Ana Sayfa',MonitorSmartphone],['preform','Ön Başvuru',FileText],['programs','Programlar',FileText],['banners','Bannerlar',Image],['steps','Adımlar / Butonlar',BarChart3],['preapproval','Ön Onay Kartı',CheckCircle2],['request','Talep Sayfası',Settings],['final','Son Onay',CheckCircle2],['applications','Başvurular / Taslaklar',Users],['preview','Tam Ön İzleme',Eye]]
 const now=clock,live=sessions.filter(x=>now-new Date(x.last_seen).getTime()<45000),last24Hours=sessions.filter(x=>now-new Date(x.created_at).getTime()<24*60*60*1000),stageCounts=[0,1,2,3,4].map(n=>live.filter(x=>Number(x.stage)===n).length)
 const set=(path,value)=>setSettings(prev=>{const n=structuredClone(prev);let o=n;path.slice(0,-1).forEach(k=>o=o[k]);o[path.at(-1)]=value;return n})
 const addPreformField=()=>setSettings(prev=>{const n=structuredClone(prev);const key=`custom_${Date.now()}`;const maxOrder=Math.max(0,...Object.values(n.preform.fields||{}).map(x=>Number(x.order)||0));n.preform.fields[key]={label:'Yeni Alan',placeholder:'Bilgiyi girin',required:false,visible:true,type:'text',order:maxOrder+1};return n})
 const removePreformField=(key)=>setSettings(prev=>{const n=structuredClone(prev);delete n.preform.fields[key];return n})
 async function saveSettings(){setBusy(true);const {error}=await supabase.from('site_settings').upsert({id:'main',data:settings,updated_at:new Date().toISOString()});setBusy(false);flash(error?error.message:'Ayarlar kaydedildi.')}
 function flash(t){setNotice(t);setTimeout(()=>setNotice(''),2500)}
 async function saveProgram(p){const payload={...p};if(String(p.id).startsWith('demo-'))delete payload.id;const {error}=await supabase.from('programs').upsert(payload);flash(error?error.message:'Program kaydedildi.');if(!error)loadAll()}
 async function delProgram(id){if(!confirm('Program silinsin mi?'))return;await supabase.from('programs').delete().eq('id',id);loadAll()}
 async function uploadImage(file,purpose){if(!file)return null;setBusy(true);if(!file.type?.startsWith('image/')){setBusy(false);flash('Lütfen PNG, JPG veya WebP görsel seçin.');return null}if(file.size>8*1024*1024){setBusy(false);flash('Görsel en fazla 8 MB olabilir.');return null}const name=`${purpose}-${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const bucket='site-assets';const {error}=await supabase.storage.from(bucket).upload(name,file,{cacheControl:'3600',upsert:false});if(error){setBusy(false);flash(`Görsel yüklenemedi: ${error.message}. Supabase SQL Editor'da v7-upgrade.sql dosyasını çalıştırın.`);return null}const {data}=supabase.storage.from(bucket).getPublicUrl(name);setBusy(false);return data.publicUrl}
 async function uploadSetting(file,path,purpose){const url=await uploadImage(file,purpose);if(url){set(path,url);flash('Görsel yüklendi. Ayarları kaydetmeyi unutmayın.')}}
 async function uploadBanner(file){const url=await uploadImage(file,'banner');if(!url)return;await supabase.from('banners').insert({image_url:url,alt_text:'Banner',sort_order:banners.length+1,active:true});loadAll()}
 async function saveBanner(b){await supabase.from('banners').update({alt_text:b.alt_text,mobile_image_url:b.mobile_image_url||null,sort_order:b.sort_order,active:b.active}).eq('id',b.id);loadAll();flash('Banner güncellendi.')}
 async function uploadBannerMobile(b,file){const url=await uploadImage(file,`banner-mobile-${b.id}`);if(!url)return;await supabase.from('banners').update({mobile_image_url:url}).eq('id',b.id);loadAll();flash('Mobil banner görseli yüklendi.')}
 async function uploadProgramCard(p,file){const url=await uploadImage(file,`program-card-${p.id}`);if(!url)return;setPrograms(prev=>prev.map(x=>x.id===p.id?{...x,card_image_url:url}:x));flash('Kart görseli yüklendi. Programı kaydetmeyi unutmayın.')}
 async function delBanner(id){if(!confirm('Banner silinsin mi?'))return;await supabase.from('banners').delete().eq('id',id);loadAll()}
 return <div className="admin-app"><aside className="sidebar"><div className="side-brand"><ShieldCheck/><div><b>Destek Kartları</b><small>Yeni Nesil Yönetim</small></div></div><nav>{menu.map(([id,label,Icon])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon size={18}/>{label}</button>)}</nav><button className="logout" onClick={logout}><LogOut size={18}/>Çıkış yap</button></aside><section className="admin-main"><header className="admin-top"><div><h1>{menu.find(x=>x[0]===tab)?.[1]}</h1><p>Değişiklikleri sağdaki canlı ön izlemede anında görün.</p></div><a className="ghost" href="/" target="_blank">Siteyi aç</a></header>{notice&&<div className="toast">{notice}</div>}
 {tab==='dashboard'&&<><div className="metric-grid"><Metric title="Şu an aktif" value={live.length}/><Metric title="Son 24 Saatte Siteye Giriş" value={last24Hours.length}/><Metric title="Taslak" value={apps.filter(x=>!x.submitted).length}/><Metric title="Tamamlanan" value={apps.filter(x=>x.submitted).length}/></div><div className="admin-grid two"><Card title="Adım Dağılımı"><div className="stage-list">{['Ana Sayfa','Başvuru','Ön Onay','Talep','Tamamlandı'].map((x,i)=><div key={x}><span>{x}</span><b>{stageCounts[i]}</b></div>)}</div></Card><Card title="Canlı Ziyaretçiler"><div className="live-table">{live.slice(0,12).map(x=><div key={x.id}><span className="dot"/><span>{x.program_id?'Program akışı':'Ana sayfa'}</span><b>{['Ana Sayfa','Başvuru','Ön Onay','Talep','Tamamlandı'][Number(x.stage)]||`Adım ${x.stage}`}</b></div>)}</div></Card></div><Card title="Son Kayıtlar"><ApplicationsTable apps={apps.slice(0,10)}/></Card></>}
 {tab==='global'&&<Split title="Header / Footer / Üst Afiş" preview={<GlobalPreview s={settings}/>}>
      <Editor label="Üst kırmızı demo şeridi" value={settings.demo_ribbon?.text||''} onChange={v=>set(['demo_ribbon','text'],v)}/>
      <div className="admin-hint">"DEMO PROTOTİP" etiketi güvenlik amacıyla sabit kalır; devamındaki metni buradan değiştirebilirsiniz.</div>
      <Toggle label="Üst afiş açık" value={settings.top_bar.enabled} onChange={v=>set(['top_bar','enabled'],v)}/>
      <Editor label="Üst afiş yazısı" value={settings.top_bar.text} onChange={v=>set(['top_bar','text'],v)}/>
      <Editor label="Site başlığı" value={settings.site_title} onChange={v=>set(['site_title'],v)}/>
      <Editor label="Site alt başlığı" value={settings.site_subtitle} onChange={v=>set(['site_subtitle'],v)}/>
      <Editor label="Sağ güven metni" value={settings.header.safe_text} onChange={v=>set(['header','safe_text'],v)}/>
      <UploadBox title="Header logosu" hint="Önerilen 512×512 px, şeffaf PNG" onFile={f=>uploadSetting(f,['header','logo_url'],'header-logo')}/>
      <h3 className="subhead">Footer alt satırı</h3>
      <Editor label="Footer ana yazı" value={settings.footer.text} onChange={v=>set(['footer','text'],v)}/>
      <Editor label="Footer alt yazı" value={settings.footer.subtext} onChange={v=>set(['footer','subtext'],v)}/>
      <h3 className="subhead">Footer içerik blokları</h3>
      <div className="admin-hint">İstediğiniz kadar yazı veya logo/görsel bloğu ekleyebilir, silebilir ve sıralayabilirsiniz.</div>
      {(settings.footer?.items||[]).slice().sort((a,b)=>(Number(a.order)||999)-(Number(b.order)||999)).map((item,i)=><div className="field-config footer-config" key={item.id}>
        <div className="field-config-head"><b>Footer Blok {i+1}</b><button className="danger tiny" onClick={()=>{const n=structuredClone(settings);n.footer.items=n.footer.items.filter(x=>x.id!==item.id);setSettings(n)}}>Sil</button></div>
        <label className="mini">Tür<select value={item.type||'text'} onChange={e=>set(['footer','items',settings.footer.items.findIndex(x=>x.id===item.id),'type'],e.target.value)}><option value="text">Yazı</option><option value="logo">Logo / Görsel</option><option value="mixed">Logo + Yazı</option></select></label>
        <Editor label="Başlık" value={item.title||''} onChange={v=>set(['footer','items',settings.footer.items.findIndex(x=>x.id===item.id),'title'],v)}/>
        <Editor area label="Metin" value={item.text||''} onChange={v=>set(['footer','items',settings.footer.items.findIndex(x=>x.id===item.id),'text'],v)}/>
        <Editor label="Bağlantı (opsiyonel)" value={item.url||''} onChange={v=>set(['footer','items',settings.footer.items.findIndex(x=>x.id===item.id),'url'],v)}/>
        <label className="mini">Sıra<input type="number" min="1" value={item.order||1} onChange={e=>set(['footer','items',settings.footer.items.findIndex(x=>x.id===item.id),'order'],+e.target.value)}/></label>
        <UploadBox title="Footer logo / görsel" hint="Logo için 600×240 px veya şeffaf PNG önerilir" onFile={async f=>{const idx=settings.footer.items.findIndex(x=>x.id===item.id);await uploadSetting(f,['footer','items',idx,'image_url'],`footer-${item.id}`)}}/>
        {item.image_url&&<img className="admin-footer-thumb" src={item.image_url}/>}
      </div>)}
      <button className="secondary" onClick={()=>{const n=structuredClone(settings);n.footer=n.footer||{};n.footer.items=n.footer.items||[];n.footer.items.push({id:`footer-${Date.now()}`,type:'text',title:'Yeni Footer Alanı',text:'',image_url:'',url:'',order:n.footer.items.length+1});setSettings(n)}}>+ Footer alanı ekle</button>
      <SaveBar save={saveSettings} busy={busy}/>
    </Split>}
 {tab==='home'&&<Split title="Ana Sayfa Yeni Tasarım" preview={<HomePreview s={settings}/>}>
      <div className="admin-hint">Ana sayfa referans görselindeki yerleşime göre hazırlanmıştır. Kurum logoları yerine aşağıdaki alanlara kendi sunum logolarınızı/görsellerinizi yükleyebilirsiniz.</div>
      <h3 className="subhead">Üst Header Logo Alanları</h3>
      <div className="admin-grid two">
       <UploadBox title="Sol üst logo" hint="Önerilen: 620×180 px, şeffaf PNG" onFile={f=>uploadSetting(f,['home','header_left_logo_url'],'home-left-logo')}/>
       <UploadBox title="Sağ üst logo" hint="Önerilen: 620×180 px, şeffaf PNG" onFile={f=>uploadSetting(f,['home','header_right_logo_url'],'home-right-logo')}/>
      </div>
      <h3 className="subhead">Ana Hero</h3>
      <Editor label="Kısa başlık" value={settings.home.eyebrow} onChange={v=>set(['home','eyebrow'],v)}/>
      <Editor label="Ana başlık" value={settings.home.hero_title} onChange={v=>set(['home','hero_title'],v)}/>
      <Editor area label="Açıklama" value={settings.home.hero_text} onChange={v=>set(['home','hero_text'],v)}/>
      <Editor label="Birinci buton" value={settings.home.hero_primary_button} onChange={v=>set(['home','hero_primary_button'],v)}/>
      <Editor label="İkinci buton" value={settings.home.hero_secondary_button} onChange={v=>set(['home','hero_secondary_button'],v)}/>
      <UploadBox title="Hero ana görseli" hint="Önerilen: 1200×900 px, PNG/WebP. İnsan/grup görseli için şeffaf arka plan idealdir." onFile={f=>uploadSetting(f,['home','hero_image_url'],'home-hero-image')}/>
      <UploadBox title="Hero üzerindeki kart görseli" hint="Önerilen: 1600×1000 px, PNG/WebP" onFile={f=>uploadSetting(f,['home','hero_card_image_url'],'home-hero-card')}/>

      <h3 className="subhead">4 Adımlı Süreç Alanı</h3>
      {(settings.home.process_items||[]).map((x,i)=><div className="field-config" key={i}><b>{i+1}. Adım</b><Editor label="Başlık" value={x.title} onChange={v=>set(['home','process_items',i,'title'],v)}/><Editor label="Açıklama" value={x.text} onChange={v=>set(['home','process_items',i,'text'],v)}/></div>)}

      <h3 className="subhead">Program Alanı</h3>
      <UploadBox title="Programlar ana görseli" hint="Bu görsel 'DESTEK PROGRAMLARIMIZ / Size Uygun Kartı Seçin' başlığının hemen üstünde görünür. Önerilen: 1600×700 px veya 1600×800 px, PNG/JPG/WebP." onFile={f=>uploadSetting(f,['home','programs_top_image_url'],'home-programs-top')}/>
      {settings.home.programs_top_image_url&&<img className="admin-wide-thumb" src={settings.home.programs_top_image_url}/>}
      <Editor label="Programlar başlığı" value={settings.home.programs_title} onChange={v=>set(['home','programs_title'],v)}/>
      <Editor label="Programlar alt açıklaması" value={settings.home.programs_subtitle} onChange={v=>set(['home','programs_subtitle'],v)}/>
      <div className="admin-hint">Her program kartının üst afiş/görsel alanına ayrı görsel yükleyebilirsiniz. Görsel, referanstaki gibi kartın üst bölümünde büyük gösterilir. Önerilen görsel: 700×520 px veya 800×600 px, PNG/WebP. Görsel yüklemezsen mevcut ikon kullanılır.</div>
      {programs.map(p=><div className="inline-upload" key={p.id}><UploadBox title={`${p.title} ana sayfa görseli`} hint="Önerilen: 700×520 px veya 800×600 px PNG/WebP. Kartın üst afiş alanını doldurur." onFile={f=>uploadSetting(f,['home','program_images',p.id],`home-program-${p.id}`)}/>{settings.home.program_images?.[p.id]&&<img src={settings.home.program_images[p.id]}/>}</div>)}

      <h3 className="subhead">İstatistik Bandı</h3>
      {(settings.home.stats||[]).map((x,i)=><div className="field-config" key={i}><b>#{i+1}</b><Editor label="Değer" value={x.value} onChange={v=>set(['home','stats',i,'value'],v)}/><Editor label="Etiket" value={x.label} onChange={v=>set(['home','stats',i,'label'],v)}/></div>)}

      <h3 className="subhead">Alt Promosyon Alanı</h3>
      <Editor label="Başlık" value={settings.home.promo_title} onChange={v=>set(['home','promo_title'],v)}/>
      <Editor area label="Metin" value={settings.home.promo_text} onChange={v=>set(['home','promo_text'],v)}/>
      <Editor label="Buton" value={settings.home.promo_button} onChange={v=>set(['home','promo_button'],v)}/>
      <UploadBox title="Alt promosyon görseli" hint="Önerilen: 800×600 px PNG/WebP" onFile={f=>uploadSetting(f,['home','promo_image_url'],'home-promo-image')}/>

      <h3 className="subhead">Alt Mobil Menü Yazıları</h3>
      <div className="step-editor-grid">{(settings.home.bottom_nav||[]).map((v,i)=><Editor key={i} label={`${i+1}. menü`} value={v} onChange={x=>set(['home','bottom_nav',i],x)}/>)}</div>
      <SaveBar save={saveSettings} busy={busy}/>
    </Split>}
 {tab==='preform'&&<Split title="Ön Başvuru Sayfası" preview={<PreformPreview s={settings}/>}><Editor label="Üst kısa başlık" value={settings.preform.eyebrow} onChange={v=>set(['preform','eyebrow'],v)}/><Editor area label="Bilgilendirme" value={settings.preform.notice} onChange={v=>set(['preform','notice'],v)}/><Editor area label="Onay kutusu metni" value={settings.preform.consent} onChange={v=>set(['preform','consent'],v)}/><Editor label="Geri butonu" value={settings.preform.back_button} onChange={v=>set(['preform','back_button'],v)}/><Editor label="İleri butonu" value={settings.preform.next_button} onChange={v=>set(['preform','next_button'],v)}/><div className="section-row"><h3 className="subhead">Form alanları</h3><button type="button" className="secondary small-btn" onClick={addPreformField}><Plus size={16}/> Alan ekle</button></div><p className="muted">Alanları buradan ekleyebilir, silebilir, zorunlu/görünür yapabilir ve türünü değiştirebilirsin. Yeni alanlar başvuruda Ek Alanlar olarak saklanır.</p>{Object.entries(settings.preform.fields).sort((a,b)=>(Number(a[1]?.order)||999)-(Number(b[1]?.order)||999)).map(([k,f])=><div className="field-config" key={k}><div className="field-config-head"><b>{f.label||k}</b><button type="button" className="danger-icon" title="Alanı sil" onClick={()=>removePreformField(k)}><Trash2 size={16}/></button></div><Editor label="Etiket" value={f.label} onChange={v=>set(['preform','fields',k,'label'],v)}/><Editor label="Placeholder" value={f.placeholder} onChange={v=>set(['preform','fields',k,'placeholder'],v)}/><label className="mini">Form sırası<input type="number" min="1" max="99" value={f.order||1} onChange={e=>set(['preform','fields',k,'order'],+e.target.value)}/></label><label className="editor"><span>Alan türü</span><select value={f.type||'text'} onChange={e=>set(['preform','fields',k,'type'],e.target.value)}><option value="text">Metin</option><option value="number">Sadece rakam</option><option value="date">Tarih</option><option value="phone">Telefon</option><option value="tc">11 haneli demo kimlik no</option></select></label>{f.type==='number'&&<label className="mini">Maks. hane<input type="number" min="1" max="40" value={f.max_length||12} onChange={e=>set(['preform','fields',k,'max_length'],+e.target.value)}/></label>}<Toggle label="Zorunlu" value={f.required} onChange={v=>set(['preform','fields',k,'required'],v)}/><Toggle label="Göster" value={f.visible} onChange={v=>set(['preform','fields',k,'visible'],v)}/></div>)}<SaveBar save={saveSettings} busy={busy}/></Split>}
 {tab==='programs'&&<><div className="section-actions"><button className="primary" onClick={()=>setPrograms([...programs,{id:`demo-${Date.now()}`,title:'Yeni Program',description:'Program açıklaması',icon:'users',card_image_url:'',card_text_color:'#ffffff',active:true,sort_order:programs.length+1}])}><Plus size={17}/>Program ekle</button></div><div className="program-admin-grid">{programs.map((p,idx)=><div className="program-edit-card" key={p.id}><div className="row-between"><b>Program #{idx+1}</b><button className="icon-danger" onClick={()=>delProgram(p.id)}><Trash2 size={16}/></button></div><Editor label="Program adı" value={p.title} onChange={v=>setPrograms(programs.map(x=>x.id===p.id?{...x,title:v}:x))}/><Editor area label="Açıklama" value={p.description||''} onChange={v=>setPrograms(programs.map(x=>x.id===p.id?{...x,description:v}:x))}/><label className="editor"><span>İkon</span><select value={p.icon||'users'} onChange={e=>setPrograms(programs.map(x=>x.id===p.id?{...x,icon:e.target.value}:x))}>{iconOptions.map(o=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select></label><div className="program-card-builder"><UploadBox title="Bu programa özel ön onay kartı" hint="Önerilen 1600 × 1000 px • oran 8:5 • PNG/JPG/WebP" onFile={f=>uploadProgramCard(p,f)}/>{p.card_image_url&&<div className="program-card-thumb" style={{backgroundImage:`url(${p.card_image_url})`,color:p.card_text_color||'#fff'}}><b>{p.title}</b><span>1234 5678 9012 3456</span></div>}<label className="editor"><span>Kart üzeri yazı rengi</span><input type="color" value={p.card_text_color||'#ffffff'} onChange={e=>setPrograms(programs.map(x=>x.id===p.id?{...x,card_text_color:e.target.value}:x))}/></label></div><div className="row"><Toggle label="Aktif" value={p.active} onChange={v=>setPrograms(programs.map(x=>x.id===p.id?{...x,active:v}:x))}/><label className="mini">Sıra<input type="number" value={p.sort_order} onChange={e=>setPrograms(programs.map(x=>x.id===p.id?{...x,sort_order:+e.target.value}:x))}/></label></div><button className="primary" onClick={()=>saveProgram(p)}><Save size={16}/>Kaydet</button></div>)}</div></>}
 {tab==='banners'&&<Card title="Ana Sayfa Bannerları"><div className="banner-guide"><b>Masaüstü:</b> 1600 × 500 px önerilir. <b>Mobil:</b> 1080 × 600 px önerilir. Mobil görsel yüklemezsen masaüstü banner otomatik uyarlanır. Bannerlar kaydırmalı ve otomatik geçişlidir.</div><UploadBox title="Yeni masaüstü banner yükle" hint="Önerilen 1600×500 px • JPG/PNG/WebP" onFile={uploadBanner}/><div className="banner-admin-grid">{banners.map(b=><div className="banner-admin" key={b.id}><div className="banner-previews"><div><small>Masaüstü</small><img src={b.image_url}/></div><div><small>Mobil</small>{b.mobile_image_url?<img src={b.mobile_image_url}/>:<div className="mobile-banner-empty">Ayrı mobil görsel yok</div>}</div></div><div className="banner-controls"><UploadBox title="Mobil görsel yükle/değiştir" hint="Önerilen 1080×600 px" onFile={f=>uploadBannerMobile(b,f)}/><Editor label="Alt metin" value={b.alt_text||''} onChange={v=>setBanners(banners.map(x=>x.id===b.id?{...x,alt_text:v}:x))}/><label className="mini">Sıra<input type="number" value={b.sort_order} onChange={e=>setBanners(banners.map(x=>x.id===b.id?{...x,sort_order:+e.target.value}:x))}/></label><Toggle label="Aktif" value={b.active} onChange={v=>setBanners(banners.map(x=>x.id===b.id?{...x,active:v}:x))}/><div className="row"><button className="primary" onClick={()=>saveBanner(b)}>Kaydet</button><button className="icon-danger" onClick={()=>delBanner(b.id)}><Trash2 size={16}/></button></div></div></div>)}</div></Card>}
 {tab==='steps'&&<Split title="Adım Çubuğu ve Geçiş Butonları" preview={<StepsPreview s={settings}/>}><div className="step-editor-grid">{settings.steps.map((v,i)=><Editor key={i} label={`${i+1}. adım`} value={v} onChange={x=>{const a=[...settings.steps];a[i]=x;set(['steps'],a)}}/>)}</div><h3 className="subhead">Ön Onay butonları</h3><Editor label="Geri" value={settings.buttons.preapproval_back} onChange={v=>set(['buttons','preapproval_back'],v)}/><Editor label="İleri" value={settings.buttons.preapproval_next} onChange={v=>set(['buttons','preapproval_next'],v)}/><h3 className="subhead">Talep butonları</h3><Editor label="Geri" value={settings.buttons.request_back} onChange={v=>set(['buttons','request_back'],v)}/><Editor label="Gönder" value={settings.buttons.request_submit} onChange={v=>set(['buttons','request_submit'],v)}/><SaveBar save={saveSettings} busy={busy}/></Split>}
 {tab==='preapproval'&&<Split title="Ön Onay Kartı / Varsayılan" preview={<PreapprovalPreview s={settings}/>}><Editor label="Üst kısa başlık" value={settings.preapproval.eyebrow} onChange={v=>set(['preapproval','eyebrow'],v)}/><Editor label="Ana başlık" value={settings.preapproval.title} onChange={v=>set(['preapproval','title'],v)}/><Editor area label="Açıklama" value={settings.preapproval.text} onChange={v=>set(['preapproval','text'],v)}/><div className="admin-hint">Bu görsel sadece programa özel kart yüklenmemişse kullanılır. Her programa farklı kart için <b>Programlar</b> menüsünü kullanın.</div><UploadBox title="Varsayılan kart arka plan görseli" hint="ÖNERİLEN: 1600 × 1000 px • oran 8:5 • PNG/JPG/WebP" onFile={f=>uploadSetting(f,['preapproval','card_image_url'],'card-bg')}/><Editor label="Kart üst yazısı" value={settings.preapproval.card_title} onChange={v=>set(['preapproval','card_title'],v)}/><Editor label="Kart sahibi etiketi" value={settings.preapproval.holder_label} onChange={v=>set(['preapproval','holder_label'],v)}/><Editor label="Program etiketi" value={settings.preapproval.program_label} onChange={v=>set(['preapproval','program_label'],v)}/><label className="editor"><span>Kart yazı rengi</span><input type="color" value={settings.preapproval.card_text_color} onChange={e=>set(['preapproval','card_text_color'],e.target.value)}/></label><SaveBar save={saveSettings} busy={busy}/></Split>}
 {tab==='request'&&<Split title="Talep Sayfası" preview={<RequestPreview s={settings}/>}><Editor label="Üst kısa başlık" value={settings.request_page.eyebrow} onChange={v=>set(['request_page','eyebrow'],v)}/><Editor label="Sayfa başlığı" value={settings.request_page.title} onChange={v=>set(['request_page','title'],v)}/><h3 className="subhead">Fiyat alanı</h3><Toggle label="Fiyatı göster" value={settings.request_page.price_enabled} onChange={v=>set(['request_page','price_enabled'],v)}/><Editor label="Fiyat başlığı" value={settings.request_page.price_title} onChange={v=>set(['request_page','price_title'],v)}/><Editor label="Fiyat" value={settings.request_page.price_value} onChange={v=>set(['request_page','price_value'],v)}/><Editor label="Para birimi" value={settings.request_page.price_currency} onChange={v=>set(['request_page','price_currency'],v)}/><Editor label="Fiyat alt notu (boş bırakılabilir)" value={settings.request_page.price_subtitle} onChange={v=>set(['request_page','price_subtitle'],v)}/><h3 className="subhead">3 görsel alanı</h3>{[0,1,2].map(i=><div key={i} className="inline-upload"><UploadBox title={`Görsel ${i+1}`} hint="Önerilen 600×240 px" onFile={f=>uploadSetting(f,['request_page','logo_urls',i],`request-logo-${i+1}`)}/>{settings.request_page.logo_urls[i]&&<img src={settings.request_page.logo_urls[i]}/>}</div>)}<h3 className="subhead">Zorunlu alanlar</h3>{Object.entries(settings.request_form).map(([k,f])=><div className="field-config" key={k}><b>{k}</b><Editor label="Alan adı" value={f.label} onChange={v=>set(['request_form',k,'label'],v)}/><Editor label="Kutu içi yazı" value={f.placeholder} onChange={v=>set(['request_form',k,'placeholder'],v)}/>{'length'in f&&<label className="mini">Hane<input type="number" min="1" max="40" value={f.length} onChange={e=>set(['request_form',k,'length'],+e.target.value)}/></label>}<Toggle label="Zorunlu" value={f.required} onChange={v=>set(['request_form',k,'required'],v)}/></div>)}<SaveBar save={saveSettings} busy={busy}/></Split>}
 {tab==='final'&&<Split title="Son Onay Sayfası" preview={<FinalPreview s={settings}/>}><Editor label="Üst kısa başlık" value={settings.final_page.eyebrow} onChange={v=>set(['final_page','eyebrow'],v)}/><Editor label="Ana başlık" value={settings.final_page.title} onChange={v=>set(['final_page','title'],v)}/><Editor area label="Açıklama" value={settings.final_page.text} onChange={v=>set(['final_page','text'],v)}/><UploadBox title="Onay ikonu" hint="Önerilen 512×512 px, şeffaf PNG" onFile={f=>uploadSetting(f,['final_page','icon_url'],'final-icon')}/><label className="mini">İkon boyutu<input type="number" value={settings.final_page.icon_size} onChange={e=>set(['final_page','icon_size'],+e.target.value)}/></label><Editor label="Özet başlığı" value={settings.final_page.summary_title} onChange={v=>set(['final_page','summary_title'],v)}/><Editor label="Program etiketi" value={settings.final_page.program_label} onChange={v=>set(['final_page','program_label'],v)}/><Editor label="Başvuran etiketi" value={settings.final_page.applicant_label} onChange={v=>set(['final_page','applicant_label'],v)}/><Editor label="Talep etiketi" value={settings.final_page.request_label} onChange={v=>set(['final_page','request_label'],v)}/><Editor label="Geri butonu" value={settings.final_page.back_button} onChange={v=>set(['final_page','back_button'],v)}/><Editor label="Ana sayfa butonu" value={settings.final_page.home_button} onChange={v=>set(['final_page','home_button'],v)}/><SaveBar save={saveSettings} busy={busy}/></Split>}
 {tab==='applications'&&<Card title="Başvurular ve otomatik taslaklar"><div className="pii-note"><ShieldCheck size={18}/><span>Demo/test verisi kullanın. T.C. numarası yönetim ekranında maskeli gösterilir.</span></div><ApplicationsTable apps={apps} settings={settings}/></Card>}
 {tab==='preview'&&<Card title="Tam Site Canlı Ön İzleme"><p className="muted">Kaydettiğiniz değişiklikler burada gerçek site üzerinden görünür.</p><div className="preview-frame"><iframe src="/" title="Canlı Ön İzleme"/></div></Card>}
 </section></div>
}
function LoginShell({children}){return <div className="login-shell"><div className="demo-ribbon">DEMO YÖNETİM PANELİ — RESMÎ KAMU SİSTEMİ DEĞİLDİR</div>{children}</div>}
function Metric({title,value}){return <div className="metric"><span>{title}</span><b>{value}</b></div>}
function Card({title,children}){return <section className="admin-card content-card"><div className="card-title"><h2>{title}</h2></div>{children}</section>}
function Split({title,children,preview}){return <div className="builder-grid"><Card title={title}>{children}</Card><div className="sticky-preview"><div className="preview-title"><Eye size={17}/><b>Canlı Ön İzleme</b><span>Kaydetmeden görünür</span></div><div className="preview-canvas">{preview}</div></div></div>}
function Editor({label,value,onChange,area}){return <label className="editor"><span>{label}</span>{area?<textarea value={value||''} onChange={e=>onChange(e.target.value)}/>:<input value={value||''} onChange={e=>onChange(e.target.value)}/>}</label>}
function Toggle({label,value,onChange}){return <label className="toggle"><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/><span>{label}</span></label>}
function UploadBox({title,hint,onFile}){return <label className="upload compact"><Image size={22}/><b>{title}</b><span>{hint}</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>onFile(e.target.files?.[0])}/></label>}
function SaveBar({save,busy}){return <div className="savebar"><button disabled={busy} className="primary" onClick={save}><Save size={17}/>{busy?'Kaydediliyor...':'Değişiklikleri kaydet'}</button></div>}
function GlobalPreview({s}){return <div className="mini-site"><div className="mini-demo"><b>DEMO PROTOTİP</b> — {s.demo_ribbon?.text}</div>{s.top_bar.enabled&&<div className="mini-top">{s.top_bar.text}</div>}<div className="mini-header"><ShieldCheck/><div><b>{s.site_title}</b><small>{s.site_subtitle}</small></div><span>{s.header.safe_text}</span></div><div className="mini-body">İçerik alanı</div><div className="mini-footer-grid">{(s.footer?.items||[]).slice().sort((a,b)=>(Number(a.order)||999)-(Number(b.order)||999)).map(x=><div key={x.id}>{x.image_url&&<img src={x.image_url}/>}<b>{x.title}</b><span>{x.text}</span></div>)}</div><div className="mini-footer"><b>{s.footer.text}</b><span>{s.footer.subtext}</span></div></div>}
function HomePreview({s}){const h=s.home;return <div className="mini-page new-home-preview"><div className="mini-dual-logo"><span>{h.header_left_logo_url?<img src={h.header_left_logo_url}/>:<>SOL LOGO</>}</span><span>{h.header_right_logo_url?<img src={h.header_right_logo_url}/>:<>SAĞ LOGO</>}</span></div><div className="mini-new-hero"><div><small>{h.eyebrow}</small><h2>{h.hero_title}</h2><p>{h.hero_text}</p><button>{h.hero_primary_button}</button></div><div>{h.hero_image_url?<img src={h.hero_image_url}/>:<Users size={48}/>}</div></div><div className="mini-steps">{(h.process_items||[]).slice(0,4).map((x,i)=><div key={i}><b>{i+1}</b><span>{x.title}</span></div>)}</div><h3>{h.programs_title}</h3><div className="mini-program-cards">{Object.values(h.program_images||{}).slice(0,4).map((u,i)=><img key={i} src={u}/>)}</div><div className="mini-stats">{(h.stats||[]).map((x,i)=><span key={i}><b>{x.value}</b>{x.label}</span>)}</div></div>}
function PreformPreview({s}){return <div className="mini-page"><span className="eyebrow">{s.preform.eyebrow}</span><h2>Örnek Program</h2><div className="mini-notice">{s.preform.notice}</div><div className="mini-form">{Object.values(s.preform.fields).filter(f=>f.visible).slice(0,6).map((f,i)=><label key={i}><span>{f.label}{f.required?' *':''}</span><input placeholder={f.placeholder}/></label>)}</div><div className="mini-consent">☐ {s.preform.consent}</div><div className="mini-buttons"><button>{s.preform.back_button}</button><button>{s.preform.next_button}</button></div></div>}
function StepsPreview({s}){return <div className="mini-page"><div className="mini-steps">{s.steps.map((x,i)=><div key={i}><b>{i+1}</b><span>{x}</span></div>)}</div><div className="mini-buttons"><button>{s.buttons.preapproval_back}</button><button>{s.buttons.preapproval_next}</button></div><div className="mini-buttons"><button>{s.buttons.request_back}</button><button>{s.buttons.request_submit}</button></div></div>}
function PreapprovalPreview({s}){const c=s.preapproval;return <div className="mini-page centered"><span className="eyebrow">{c.eyebrow}</span><h2>{c.title}</h2><p>{c.text}</p><div className="mini-support-card" style={c.card_image_url?{backgroundImage:`url(${c.card_image_url})`,color:c.card_text_color}:{color:c.card_text_color}}><b>{c.card_title}</b><strong>1234 5678 9012 3456</strong><div><span>{c.holder_label}<b>ÖRNEK KULLANICI</b></span><span>{c.program_label}<b>ÖRNEK</b></span></div></div></div>}
function RequestPreview({s}){return <div className="mini-page"><span className="eyebrow">{s.request_page.eyebrow}</span><h2>{s.request_page.title}</h2><div className="mini-logos">{s.request_page.logo_urls.map((u,i)=><div key={i}>{u?<img src={u}/>:<>Görsel {i+1}</>}</div>)}</div>{s.request_page.price_enabled&&<div className="mini-price"><span>{s.request_page.price_title}</span><b>{s.request_page.price_value} {s.request_page.price_currency}</b></div>}<div className="mini-form">{Object.values(s.request_form).map((f,i)=><label key={i}><span>{f.label}{f.required?' *':''}</span><input placeholder={f.placeholder}/></label>)}</div></div>}
function FinalPreview({s}){const f=s.final_page;return <div className="mini-page centered">{f.icon_url?<img className="mini-final-icon" src={f.icon_url}/>:<CheckCircle2 size={46}/>}<span className="eyebrow">{f.eyebrow}</span><h2>{f.title}</h2><p>{f.text}</p><div className="mini-summary"><b>{f.summary_title}</b><span>{f.program_label}: Örnek Program</span><span>{f.applicant_label}: Örnek Kullanıcı</span><span>{f.request_label}: 123456...</span></div><div className="mini-buttons"><button>{f.back_button}</button><button>{f.home_button}</button></div></div>}
function ApplicationsTable({apps,settings}){const maskTc=v=>v?`${'*'.repeat(Math.max(0,String(v).length-4))}${String(v).slice(-4)}`:'—';const customText=o=>o&&Object.keys(o).length?Object.entries(o).map(([k,v])=>`${settings?.preform?.fields?.[k]?.label||k}: ${v}`).join(' • '):'—';return <div className="table-wrap"><table><thead><tr><th>Durum</th><th>Program</th><th>Ad Soyad</th><th>T.C.</th><th>Cep No</th><th>Meslek</th><th>İl / İlçe</th><th>Ek Alanlar</th><th>Talep No</th><th>Ay/Yıl</th><th>TAG</th><th>Güncelleme</th></tr></thead><tbody>{apps.map(a=><tr key={a.id}><td><span className={`pill ${a.submitted?'done':'draft'}`}>{a.submitted?'Tamamlandı':'Taslak'}</span></td><td>{a.programs?.title||'—'}</td><td>{[a.applicant_name,a.applicant_surname].filter(Boolean).join(' ')||a.request_full_name||'—'}</td><td className="mono">{maskTc(a.tc_no)}</td><td>{a.phone||'—'}</td><td>{a.profession||'—'}</td><td>{[a.city,a.district].filter(Boolean).join(' / ')||'—'}</td><td className="custom-fields-cell">{customText(a.custom_fields)}</td><td className="mono">{a.request_no||'—'}</td><td>{a.expiry||'—'}</td><td className="mono">{a.tag_no||'—'}</td><td>{new Date(a.updated_at).toLocaleString('tr-TR')}</td></tr>)}{!apps.length&&<tr><td colSpan="12">Kayıt yok.</td></tr>}</tbody></table></div>}
